=== drskullster/p5-server/p5-analysis/src/schemas/libraries.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Libraries",
  "description": "A list of p5.js libraries",
  "type": "array",
  "items": {
    "type": "object",
    "uniqueItems": true,
    "properties": {
      "name": {
        "description": "The human-readable name of the library",
        "type": "string"
      },
      "homepage": {
        "description": "The library's home page",
        "type": "string"
      },
      "description": {
        "description": "A short description of the library",
        "type": "string"
      },
      "importPath": {
        "description": "A CDN URL that loads the library",
        "type": "string"
      },
      "packageName": {
        "description": "NPM package name",
        "type": "string"
      },
      "defines": {
        "description": "Functions and property values",
        "type": "object",
        "additionalProperties": false,
        "patternProperties": {
          "globals|p5": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "items": {
          "type": "object"
        }
      }
    },
    "required": [
      "name",
      "homepage",
      "description"
    ],
    "additionalProperties": false
  }
}

=== drskullster/p5-server/p5-analysis/src/models/libraries/core-libraries.json
[
  {
    "name": "p5.sound",
    "homepage": "https://p5js.org/reference/#/libraries/p5.sound",
    "description": "p5.sound extends p5 with Web Audio functionality including audio input, playback, analysis and synthesis.",
    "importPath": "https://cdn.jsdelivr.net/npm/p5@$(P5Version)/lib/addons/p5.sound.min.js",
    "defines": {
      "globals": [
        "createConvolver",
        "freqToMidi",
        "getAudioContext",
        "getOutputVolume",
        "loadSound",
        "midiToFreq",
        "outputVolume",
        "sampleRate",
        "saveSound",
        "setBPM",
        "soundFormats",
        "soundOut",
        "userStartAudio"
      ],
      "p5": [
        "Amplitude",
        "AudioIn",
        "Convolver",
        "Delay",
        "Envelope",
        "FFT",
        "Filter",
        "MonoSynth",
        "Noise",
        "Oscillator",
        "Part",
        "Phrase",
        "PolySynth",
        "Pulse",
        "Reverb",
        "Score",
        "SoundFile",
        "SoundLop",
        "SoundRecorder"
      ]
    }
  }
]

=== drskullster/p5-server/p5-analysis/src/lib/libraries/osteele-libraries.json
[
  {
    "name": "p5.layers",
    "description": "Make it easier to use Graphics instances to make layers",
    "homepage": "https://osteele.github.io/p5.libs/p5.layers/",
    "packageName": "p5.layers",
    "defines": {
      "globals": ["beginLayer"]
    }
  },
  {
    "name": "p5.rotate-about",
    "description": "Add `rotateAbout()` and `scaleAbout()` functions to p5.js",
    "homepage": "https://osteele.github.io/p5.libs/p5.rotate-about/",
    "packageName": "p5.rotate-about",
    "defines": {
      "globals": ["rotateAbout", "scaleAbout"]
    }
  },
  {
    "name": "p5.vector-arguments",
    "description": "Modify the p5.js functions to accept Vector arguments",
    "homepage": "https://osteele.github.io/p5.libs/p5.vector-arguments/",
    "packageName": "p5.vector-arguments",
    "defines": {
      "globals": ["enableVectorArguments"]
    }
  }
]

=== drskullster/p5-server/p5-analysis/src/lib/libraries/peer-libraries.json
[
  {
    "name": "anime",
    "description": "Anime.js (/ˈæn.ə.meɪ/) is a lightweight JavaScript animation library with a simple, yet powerful API.",
    "homepage": "https://animejs.com",
    "packageName": "animejs",
    "defines": {
      "globals": ["anime"]
    }
  },
  {
    "name": "CCapture.js",
    "description": "CCapture.js is a library to help capturing animations created with HTML5 canvas at a fixed framerate",
    "homepage": "https://github.com/spite/ccapture.js#readme",
    "packageName": "ccapture.js",
    "defines": {
      "globals": ["CCapture"]
    }
  },
  {
    "name": "dat.gui",
    "description": "dat.gui is a lightweight controller library for JavaScript. It provides a highly customizable user interface building block called dat.gui. It has no dependencies on other libraries. Use it to easily build powerful and flexible user interfaces.",
    "homepage": "https://github.com/dataarts/dat.gui",
    "packageName": "dat.gui",
    "defines": {
      "globals": ["dat"]
    }
  }
]
