=== drskullster/p5-server/config/libraries-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Libraries",
  "description": "A list of p5.js libraries",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "description": "The human-readable name of the library",
        "type": "string"
      },
      "path": {
        "description": "The path to the library file",
        "type": "string"
      },
      "globals": {
        "description": "Global variables defined by the library",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "props": {
        "description": "p5 properties added by the library",
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": [
      "name",
      "path"
    ]
  }
}

=== drskullster/p5-server/config/libraries.json
[
  {
    "name": "sound",
    "path": "https://cdn.jsdelivr.net/npm/p5@$(P5Version)/lib/addons/p5.sound.min.js",
    "globals": [
      "createConvolver",
      "freqToMidi",
      "getAudioContext",
      "getOutputVolume",
      "loadSound",
      "midiToFreq",
      "outputVolume",
      "sampleRate",
      "saveSound",
      "setBPM",
      "soundFormats",
      "soundOut",
      "userStartAudio"
    ],
    "props": [
      "Amplitude",
      "AudioIn",
      "Convolver",
      "Delay",
      "Envelope",
      "FFT",
      "Filter",
      "MonoSynth",
      "Noise",
      "Oscillator",
      "Part",
      "Phrase",
      "PolySynth",
      "Pulse",
      "Reverb",
      "Score",
      "SoundFile",
      "SoundLop",
      "SoundRecorder"
    ]
  }
]
